import type { Metadata } from "next";
import Link from "next/link";
import { DocumentPage } from "@/components/layout/DocumentPage";
export const metadata: Metadata = { title: "Datos y consentimiento", alternates: { canonical: "/privacidad" } };
export default function Page() {
  return <DocumentPage eyebrow="Información de privacidad" title="Tus datos, explicados con claridad." lead="Esta información describe el funcionamiento actual de la web de PsicoCare. Versión de consentimiento de encuesta: producto-2026-09-v1. Actualizada el 14 de septiembre de 2026.">
    <h2>Encuestas de producto</h2><p>Recopilamos preferencias sobre funciones, frecuencia de uso, expectativas y un rango de edad. Las respuestas sirven para validar interés y priorizar el desarrollo. Las preguntas no piden nombre, teléfono, fecha de nacimiento exacta ni diagnósticos. Al terminar puedes dejar tu correo de forma voluntaria; se explica más abajo.</p><p>Se guarda un identificador aleatorio del navegador, transformado en un resumen criptográfico, para recuperar respuestas y evitar envíos accidentales repetidos. No recogemos IP ni agente de usuario en la base de datos de encuestas. Las respuestas están separadas de los contactos, pero no prometemos anonimato absoluto: evita escribir información que te identifique.</p>
    <h2>Participación voluntaria y personas menores</h2><p>La primera investigación solo acepta participantes de 18 años o más. Confirmas la edad y el consentimiento antes de empezar. Si seleccionas un rango menor de edad, la participación se elimina y no se envían sus respuestas. Una investigación futura con menores necesitará un proceso específico validado antes de abrirse.</p>
    <h2>Guardado y conservación</h2><p>Al avanzar o volver en la encuesta, se guardan las respuestas en la base de datos del servidor. Los borradores caducan después de 7 días sin actividad; las respuestas completas y los contactos, después de 180 días. La limpieza se ejecuta automáticamente cuando se utiliza la base de datos, como máximo una vez por hora, y también puede programarse por el equipo.</p><p>Solo el equipo autorizado accede al panel interno, protegido con clave y sesión firmada. Los gráficos agregados exigen un mínimo de cinco respuestas completas y excluyen edad y texto libre. El equipo autorizado sí puede leer cada respuesta finalizada por separado, incluidas las respuestas de texto y el correo si lo dejaste, para entender el detalle de lo que nos cuentas. Por eso te pedimos que no escribas información que te identifique o que sea sensible.</p>
    <h2>Retirar tu participación</h2><p>Desde <Link href="/encuestas">la encuesta</Link>, elige “Retirar mi participación y borrar respuestas” en el navegador que usaste. Esto elimina tanto el borrador como la respuesta completa. Si eliminas la cookie o utilizas otro navegador, ya no podremos reconocer automáticamente cuál fue tu respuesta.</p>
    <h2>Correo opcional al terminar la encuesta</h2><p>Cuando envías tus respuestas te ofrecemos dejar un correo para avisarte sobre el avance de PsicoCare. Es opcional: puedes participar sin dejarlo y la encuesta se considera igual de completa. Solo lo guardamos si marcas la casilla de autorización o si inicias sesión con Google.</p><p>Si eliges el acceso con Google, PsicoCare solicita únicamente la dirección de correo de la cuenta y si Google la da por verificada. No accedemos a tu Gmail, tu agenda, tus contactos ni ningún otro dato, y no publicamos mensajes en tu nombre. El intercambio ocurre entre nuestro servidor y Google; no almacenamos contraseñas ni tokens de acceso.</p><p>El correo se guarda en una tabla aparte de tus respuestas y se usa solo para comunicarte novedades del proyecto. No lo vendemos ni lo compartimos con terceros. Como queda asociado a tu participación, dejarlo significa que esa participación deja de ser anónima frente al equipo autorizado. Puedes quitarlo en cualquier momento desde la pantalla final de la encuesta, con el botón “Quitar mi correo”, y si retiras tu participación se borra junto con las respuestas.</p>
    <h2>Formulario de contacto</h2><p>Si deseas que el equipo responda a una consulta, puedes proporcionar nombre, correo, organización opcional y mensaje. Debes autorizar expresamente ese uso. Los mensajes se guardan en un buzón interno separado, no se enlazan con respuestas de encuestas ni se envían a una lista de publicidad. Para una consulta sobre tus datos de contacto, utiliza <Link href="/#contacto">el formulario</Link> e indica el correo asociado. No incluyas información sensible de salud.</p>
    <h2>Cookies y demo</h2><p>La cookie necesaria de participación conserva un identificador aleatorio hasta 180 días. La cookie de acceso interno dura hasta ocho horas. Si usas el acceso con Google, se crea además una cookie temporal de diez minutos para proteger ese intercambio frente a solicitudes falsificadas. Todas son de acceso exclusivo del servidor. No incorporamos cookies publicitarias, rastreadores de terceros ni analítica comercial. Las fuentes y los recursos de marca se sirven desde esta web.</p><p>La demo no envía emociones, reflexiones ni conversaciones a servidores. La información permanece en la memoria de esa página mientras la tienes abierta.</p>
    <h2>Alojamiento y seguridad</h2><p>El equipo debe usar HTTPS, restringir el acceso a la base de datos y aplicar los mismos plazos de conservación a sus copias de seguridad. El proveedor de alojamiento puede gestionar registros técnicos de conexión ajenos a la base de datos de encuestas. Antes de una apertura pública deben concretarse las condiciones de alojamiento, la identificación del responsable y el canal de atención de solicitudes.</p>
  </DocumentPage>;
}
