import type { Metadata } from "next";
import Link from "next/link";
import { DocumentPage } from "@/components/layout/DocumentPage";
export const metadata: Metadata = { title: "Términos de uso" };
export default function Page(){return <DocumentPage eyebrow="Uso responsable" title="Condiciones para usar Psico Care." lead="Versión del 9 de octubre de 2026. Equipo del proyecto: Psico Care team, Nicaragua.">
<h2>Alcance</h2><p>Estas condiciones describen la web, su demo, las encuestas, el contacto y la distribución del APK oficial. El tratamiento de información se explica en la <Link href="/privacidad">política de privacidad</Link>; aceptar una opción de cookies no equivale a consentir una encuesta, una comunicación comercial ni permisos de la app.</p>
<h2>Acompañamiento, no atención clínica</h2><p>Los materiales y funciones de inteligencia artificial ofrecen acompañamiento e información general y pueden equivocarse. No deben usarse como diagnóstico, tratamiento, consejo médico ni base única para decisiones de salud. La app no sustituye vínculos personales ni apoyo profesional. En una emergencia, busca los servicios de emergencia de tu localidad o una persona de confianza; este sitio no monitoriza ni responde de inmediato a situaciones de crisis.</p>
<h2>Demo y funcionalidades</h2><p>La demo web utiliza conversaciones preparadas y conserva sus entradas solo mientras esa página está abierta. Las funciones institucionales, clínicas o profesionales anunciadas como en desarrollo no se ofrecen como servicios ya contratados. No se garantiza un resultado terapéutico ni disponibilidad ininterrumpida.</p>
<h2>Encuestas y cuentas</h2><p>Las encuestas actuales están dirigidas a personas de 18 años o más y requieren el consentimiento específico que aparece antes de comenzar. No envíes datos de otras personas ni información sensible de salud. Conserva tus credenciales de forma privada y no accedas a cuentas o paneles para los que no tienes autorización.</p>
<h2>Descarga Android</h2><p>Descarga el APK desde el enlace oficial publicado en esta web. La instalación es voluntaria y requiere un dispositivo compatible. Los permisos de cámara y micrófono se solicitan por separado en Android. Revisar las condiciones del sitio no concede esos permisos automáticamente. El equipo puede publicar actualizaciones; verifica la versión antes de instalar.</p>
<h2>Uso permitido</h2><p>No se permite suplantar identidades, introducir código malicioso, intentar acceder a información ajena, evadir controles de seguridad ni usar el servicio para acosar o causar daño. Compartir un enlace oficial no te autoriza a revender el servicio o atribuirte sus contenidos.</p>
<h2>Servicios externos, cambios y responsabilidad</h2><p>Los enlaces externos y proveedores aplican sus propias condiciones. Informaremos cambios relevantes mediante una versión y fecha actualizadas. No se excluye la responsabilidad que establezca la ley ni se exige renunciar a derechos. Para consultas o incidencias escribe a <a href="mailto:contacto.Psicocare26@gmail.com">contacto.Psicocare26@gmail.com</a>.</p></DocumentPage>;}
