import type { Metadata } from "next";
import Link from "next/link";
import { DocumentPage } from "@/components/layout/DocumentPage";
export const metadata: Metadata = { title: "Aviso legal" };
export default function Page(){return <DocumentPage eyebrow="Información del proyecto" title="Quién está detrás de Psico Care." lead="Actualizado el 9 de octubre de 2026.">
<h2>Equipo responsable y contacto</h2><p>El equipo responsable del proyecto y de esta web es <strong>Psico Care team</strong>, con actividad en <strong>Nicaragua</strong>. Esta denominación identifica al equipo del proyecto; no afirma una forma societaria ni un registro profesional.</p><p>Contacto para asuntos del sitio y protección de datos: <a href="mailto:contacto.Psicocare26@gmail.com">contacto.Psicocare26@gmail.com</a>. También puedes utilizar <Link href="/#contacto">el formulario de contacto</Link>.</p>
<h2>Finalidad y límites</h2><p>Psico Care es un proyecto de acompañamiento emocional y bienestar en desarrollo. La web presenta el producto, una demo, encuestas, contacto y el enlace de descarga de Android. No constituye una consulta clínica ni un servicio de emergencia; no diagnostica, prescribe ni sustituye la atención de profesionales.</p>
<h2>Marca y contenidos</h2><p>Los recursos del proyecto y los de terceros conservan los derechos de sus respectivos titulares. La disponibilidad pública no transfiere esos derechos. Puedes compartir enlaces a esta web y a la descarga oficial; no presentes una versión alterada del APK como publicación del equipo.</p>
<h2>Normas y documentos</h2><p>Las solicitudes sobre información personal se atienden conforme a la normativa aplicable, incluida la Ley N.º 787 de Protección de Datos Personales de Nicaragua cuando corresponda. Ninguna condición de esta web limita derechos que no puedan ser renunciados legalmente.</p><p><Link href="/privacidad">Política de privacidad</Link> · <Link href="/cookies">Política de cookies</Link> · <Link href="/terminos">Términos de uso</Link></p></DocumentPage>;}
