import type { Metadata } from "next";
import Link from "next/link";
import { DocumentPage } from "@/components/layout/DocumentPage";
export const metadata: Metadata = { title: "Política de cookies" };
export default function Page(){return <DocumentPage eyebrow="Cookies y preferencias" title="Decide qué quieres permitir." lead="Actualizada el 9 de octubre de 2026. Responsable del proyecto: Psico Care team, Nicaragua.">
<h2>Qué se activa al visitar la web</h2><p>Las cookies necesarias permiten guardar tu elección y proteger funciones que solicitas, como participar en una encuesta o iniciar sesión. La medición opcional de visitas no se carga antes de tu autorización. Rechazarla no impide navegar ni descargar el APK.</p>
<h2>Cookies propias necesarias</h2><ul><li><strong>pc_privacy:</strong> conserva la versión del aviso, tu decisión sobre analítica y la fecha de elección durante 180 días. No contiene tu correo ni tus respuestas.</li><li><strong>pc_participation:</strong> identificador aleatorio para recuperar una encuesta iniciada; hasta 180 días. Solo aparece cuando decides participar.</li><li><strong>pc_team:</strong> acceso del equipo al panel privado; hasta 12 horas. Solo aparece al iniciar sesión.</li><li><strong>pc_oauth:</strong> protección temporal del acceso con Google; diez minutos. Solo aparece si solicitas ese acceso.</li></ul><p>Las cookies de participación, equipo y Google son de acceso exclusivo del servidor. La de preferencias puede ser leída por esta web para respetar tu elección.</p>
<h2>Medición opcional</h2><p>Vercel Web Analytics mide visitas a páginas públicas, país, navegador y tipo de dispositivo. Este servicio no utiliza cookies, pero lo tratamos como una opción que requiere tu autorización. El panel interno está excluido y eliminamos los parámetros y fragmentos de la URL de los eventos enviados. No enviamos respuestas, correos ni mensajes a la analítica.</p><p>No utilizamos cookies publicitarias ni categorías opcionales ocultas. Consulta la <a href="https://vercel.com/docs/analytics/privacy-policy">información de privacidad de Vercel Web Analytics</a>.</p>
<h2>Cambiar o retirar tu elección</h2><p>Utiliza “Configurar cookies” en el pie de cualquier página. Puedes rechazar la medición con un solo botón. Al retirarla recargamos la página para detener el componente que la ejecuta. La elección caduca a los 180 días o si cambia la versión de este aviso; entonces volvemos a preguntarte. Retirar el permiso detiene nuevas mediciones y no borra automáticamente datos que el proveedor ya haya procesado.</p><p>También puedes borrar o bloquear cookies desde tu navegador; hacerlo puede impedir recuperar tu encuesta o cerrar tu sesión. Si el navegador no guarda tu elección, la medición permanece desactivada.</p>
<h2>Otros sitios y la aplicación Android</h2><p>La descarga del APK se sirve desde Microsoft Azure. Google y los sitios externos aplican sus propias condiciones cuando los visitas. Este aviso describe el almacenamiento de la web; no autoriza por sí mismo permisos de cámara, micrófono ni tratamiento de datos dentro de la app.</p><p><Link href="/privacidad">Privacidad</Link> · <Link href="/terminos">Términos</Link> · <Link href="/aviso-legal">Contacto del responsable</Link></p></DocumentPage>;}
